const PLEDGING_START_DATE = new Date();
const PLEDGING_END_DATE = new Date();
PLEDGING_START_DATE.setMonth(3);
PLEDGING_END_DATE.setMonth(4);
PLEDGING_START_DATE.setDate(10);

export { PLEDGING_START_DATE, PLEDGING_END_DATE };
