const PLEDGING_START_DATE = new Date();
const PLEDGING_END_DATE = new Date();
PLEDGING_START_DATE.setDate(16);
PLEDGING_START_DATE.setMonth(9);
PLEDGING_END_DATE.setMonth(0);
PLEDGING_END_DATE.setYear(2020);

export { PLEDGING_START_DATE, PLEDGING_END_DATE };
